// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package caliptra_fpga_sync_regs_pkg;

    localparam CALIPTRA_FPGA_SYNC_REGS_DATA_WIDTH = 64;
    localparam CALIPTRA_FPGA_SYNC_REGS_MIN_ADDR_WIDTH = 17;

    typedef struct {
        logic [31:0] next;
    } caliptra_fpga_sync_regs__apb_out__pdata__in_t;

    typedef struct {
        logic next;
    } caliptra_fpga_sync_regs__apb_out__pready__in_t;

    typedef struct {
        logic next;
    } caliptra_fpga_sync_regs__apb_out__pslverr__in_t;

    typedef struct {
        caliptra_fpga_sync_regs__apb_out__pdata__in_t pdata;
        caliptra_fpga_sync_regs__apb_out__pready__in_t pready;
        caliptra_fpga_sync_regs__apb_out__pslverr__in_t pslverr;
    } caliptra_fpga_sync_regs__apb_out__in_t;

    typedef struct {
        logic next;
    } caliptra_fpga_sync_regs__jtag_out__tdo__in_t;

    typedef struct {
        caliptra_fpga_sync_regs__jtag_out__tdo__in_t tdo;
    } caliptra_fpga_sync_regs__jtag_out__in_t;

    typedef struct {
        logic [63:0] next;
    } caliptra_fpga_sync_regs__generic_output_wires__value__in_t;

    typedef struct {
        caliptra_fpga_sync_regs__generic_output_wires__value__in_t value;
    } caliptra_fpga_sync_regs__generic_output_wires__in_t;

    typedef struct {
        logic next;
    } caliptra_fpga_sync_regs__status__cptra_error_fatal__in_t;

    typedef struct {
        logic next;
    } caliptra_fpga_sync_regs__status__cptra_error_non_fatal__in_t;

    typedef struct {
        logic next;
    } caliptra_fpga_sync_regs__status__ready_for_fuses__in_t;

    typedef struct {
        logic next;
    } caliptra_fpga_sync_regs__status__ready_for_fw_push__in_t;

    typedef struct {
        logic next;
    } caliptra_fpga_sync_regs__status__ready_for_runtime__in_t;

    typedef struct {
        logic next;
    } caliptra_fpga_sync_regs__status__mailbox_data_avail__in_t;

    typedef struct {
        logic next;
    } caliptra_fpga_sync_regs__status__mailbox_flow_done__in_t;

    typedef struct {
        caliptra_fpga_sync_regs__status__cptra_error_fatal__in_t cptra_error_fatal;
        caliptra_fpga_sync_regs__status__cptra_error_non_fatal__in_t cptra_error_non_fatal;
        caliptra_fpga_sync_regs__status__ready_for_fuses__in_t ready_for_fuses;
        caliptra_fpga_sync_regs__status__ready_for_fw_push__in_t ready_for_fw_push;
        caliptra_fpga_sync_regs__status__ready_for_runtime__in_t ready_for_runtime;
        caliptra_fpga_sync_regs__status__mailbox_data_avail__in_t mailbox_data_avail;
        caliptra_fpga_sync_regs__status__mailbox_flow_done__in_t mailbox_flow_done;
    } caliptra_fpga_sync_regs__status__in_t;

    typedef struct {
        logic next;
    } caliptra_fpga_sync_regs__trng_out__etrng_req__in_t;

    typedef struct {
        caliptra_fpga_sync_regs__trng_out__etrng_req__in_t etrng_req;
    } caliptra_fpga_sync_regs__trng_out__in_t;

    typedef struct {
        logic [31:0] next;
    } caliptra_fpga_sync_regs__clock_control__cycle_count__in_t;

    typedef struct {
        logic next;
    } caliptra_fpga_sync_regs__clock_control__go__in_t;

    typedef struct {
        logic hwset;
    } caliptra_fpga_sync_regs__clock_control__bkpt_generic_output_wires__in_t;

    typedef struct {
        logic hwset;
    } caliptra_fpga_sync_regs__clock_control__bkpt_mailbox_data_avail__in_t;

    typedef struct {
        logic hwset;
    } caliptra_fpga_sync_regs__clock_control__bkpt_mailbox_flow_done__in_t;

    typedef struct {
        logic hwset;
    } caliptra_fpga_sync_regs__clock_control__bkpt_etrng_req__in_t;

    typedef struct {
        caliptra_fpga_sync_regs__clock_control__cycle_count__in_t cycle_count;
        caliptra_fpga_sync_regs__clock_control__go__in_t go;
        caliptra_fpga_sync_regs__clock_control__bkpt_generic_output_wires__in_t bkpt_generic_output_wires;
        caliptra_fpga_sync_regs__clock_control__bkpt_mailbox_data_avail__in_t bkpt_mailbox_data_avail;
        caliptra_fpga_sync_regs__clock_control__bkpt_mailbox_flow_done__in_t bkpt_mailbox_flow_done;
        caliptra_fpga_sync_regs__clock_control__bkpt_etrng_req__in_t bkpt_etrng_req;
    } caliptra_fpga_sync_regs__clock_control__in_t;

    typedef struct {
        logic [63:0] next;
    } caliptra_fpga_sync_regs__counter__counter__in_t;

    typedef struct {
        caliptra_fpga_sync_regs__counter__counter__in_t counter;
    } caliptra_fpga_sync_regs__counter__in_t;

    typedef struct {
        logic rd_ack;
        logic [63:0] rd_data;
        logic wr_ack;
    } caliptra_fpga_sync_regs__rom_mem__external__in_t;

    typedef struct {
        caliptra_fpga_sync_regs__apb_out__in_t apb_out;
        caliptra_fpga_sync_regs__jtag_out__in_t jtag_out;
        caliptra_fpga_sync_regs__generic_output_wires__in_t generic_output_wires;
        caliptra_fpga_sync_regs__status__in_t status;
        caliptra_fpga_sync_regs__trng_out__in_t trng_out;
        caliptra_fpga_sync_regs__clock_control__in_t clock_control;
        caliptra_fpga_sync_regs__counter__in_t counter;
        caliptra_fpga_sync_regs__rom_mem__external__in_t rom_mem;
    } caliptra_fpga_sync_regs__in_t;

    typedef struct {
        logic [31:0] value;
    } caliptra_fpga_sync_regs__apb_in0__pdata__out_t;

    typedef struct {
        logic [31:0] value;
    } caliptra_fpga_sync_regs__apb_in0__paddr__out_t;

    typedef struct {
        caliptra_fpga_sync_regs__apb_in0__pdata__out_t pdata;
        caliptra_fpga_sync_regs__apb_in0__paddr__out_t paddr;
    } caliptra_fpga_sync_regs__apb_in0__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__apb_in1__psel__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__apb_in1__penable__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__apb_in1__pwrite__out_t;

    typedef struct {
        logic [2:0] value;
    } caliptra_fpga_sync_regs__apb_in1__pprot__out_t;

    typedef struct {
        logic [31:0] value;
    } caliptra_fpga_sync_regs__apb_in1__pauser__out_t;

    typedef struct {
        caliptra_fpga_sync_regs__apb_in1__psel__out_t psel;
        caliptra_fpga_sync_regs__apb_in1__penable__out_t penable;
        caliptra_fpga_sync_regs__apb_in1__pwrite__out_t pwrite;
        caliptra_fpga_sync_regs__apb_in1__pprot__out_t pprot;
        caliptra_fpga_sync_regs__apb_in1__pauser__out_t pauser;
    } caliptra_fpga_sync_regs__apb_in1__out_t;

    typedef struct {
        logic [31:0] value;
    } caliptra_fpga_sync_regs__apb_out__pdata__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__apb_out__pready__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__apb_out__pslverr__out_t;

    typedef struct {
        caliptra_fpga_sync_regs__apb_out__pdata__out_t pdata;
        caliptra_fpga_sync_regs__apb_out__pready__out_t pready;
        caliptra_fpga_sync_regs__apb_out__pslverr__out_t pslverr;
    } caliptra_fpga_sync_regs__apb_out__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__jtag_in__tck__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__jtag_in__tms__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__jtag_in__tdi__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__jtag_in__trst_n__out_t;

    typedef struct {
        caliptra_fpga_sync_regs__jtag_in__tck__out_t tck;
        caliptra_fpga_sync_regs__jtag_in__tms__out_t tms;
        caliptra_fpga_sync_regs__jtag_in__tdi__out_t tdi;
        caliptra_fpga_sync_regs__jtag_in__trst_n__out_t trst_n;
    } caliptra_fpga_sync_regs__jtag_in__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__jtag_out__tdo__out_t;

    typedef struct {
        caliptra_fpga_sync_regs__jtag_out__tdo__out_t tdo;
    } caliptra_fpga_sync_regs__jtag_out__out_t;

    typedef struct {
        logic [63:0] value;
    } caliptra_fpga_sync_regs__generic_input_wires__value__out_t;

    typedef struct {
        caliptra_fpga_sync_regs__generic_input_wires__value__out_t value;
    } caliptra_fpga_sync_regs__generic_input_wires__out_t;

    typedef struct {
        logic [63:0] value;
    } caliptra_fpga_sync_regs__generic_output_wires__value__out_t;

    typedef struct {
        caliptra_fpga_sync_regs__generic_output_wires__value__out_t value;
    } caliptra_fpga_sync_regs__generic_output_wires__out_t;

    typedef struct {
        logic [63:0] value;
    } caliptra_fpga_sync_regs__cptra_obf_key__value__out_t;

    typedef struct {
        caliptra_fpga_sync_regs__cptra_obf_key__value__out_t value;
    } caliptra_fpga_sync_regs__cptra_obf_key__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__control__cptra_pwrgood__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__control__cptra_rst_b__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__control__ss_debug_locked__out_t;

    typedef struct {
        logic [1:0] value;
    } caliptra_fpga_sync_regs__control__ss_device_lifecycle__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__control__scan_mode__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__control__bootfsm_brkpoint__out_t;

    typedef struct {
        caliptra_fpga_sync_regs__control__cptra_pwrgood__out_t cptra_pwrgood;
        caliptra_fpga_sync_regs__control__cptra_rst_b__out_t cptra_rst_b;
        caliptra_fpga_sync_regs__control__ss_debug_locked__out_t ss_debug_locked;
        caliptra_fpga_sync_regs__control__ss_device_lifecycle__out_t ss_device_lifecycle;
        caliptra_fpga_sync_regs__control__scan_mode__out_t scan_mode;
        caliptra_fpga_sync_regs__control__bootfsm_brkpoint__out_t bootfsm_brkpoint;
    } caliptra_fpga_sync_regs__control__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__status__cptra_error_fatal__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__status__cptra_error_non_fatal__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__status__ready_for_fuses__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__status__ready_for_fw_push__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__status__ready_for_runtime__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__status__mailbox_data_avail__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__status__mailbox_flow_done__out_t;

    typedef struct {
        caliptra_fpga_sync_regs__status__cptra_error_fatal__out_t cptra_error_fatal;
        caliptra_fpga_sync_regs__status__cptra_error_non_fatal__out_t cptra_error_non_fatal;
        caliptra_fpga_sync_regs__status__ready_for_fuses__out_t ready_for_fuses;
        caliptra_fpga_sync_regs__status__ready_for_fw_push__out_t ready_for_fw_push;
        caliptra_fpga_sync_regs__status__ready_for_runtime__out_t ready_for_runtime;
        caliptra_fpga_sync_regs__status__mailbox_data_avail__out_t mailbox_data_avail;
        caliptra_fpga_sync_regs__status__mailbox_flow_done__out_t mailbox_flow_done;
    } caliptra_fpga_sync_regs__status__out_t;

    typedef struct {
        logic [3:0] value;
    } caliptra_fpga_sync_regs__trng_in__itrng_data__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__trng_in__itrng_valid__out_t;

    typedef struct {
        caliptra_fpga_sync_regs__trng_in__itrng_data__out_t itrng_data;
        caliptra_fpga_sync_regs__trng_in__itrng_valid__out_t itrng_valid;
    } caliptra_fpga_sync_regs__trng_in__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__trng_out__etrng_req__out_t;

    typedef struct {
        caliptra_fpga_sync_regs__trng_out__etrng_req__out_t etrng_req;
    } caliptra_fpga_sync_regs__trng_out__out_t;

    typedef struct {
        logic [31:0] value;
    } caliptra_fpga_sync_regs__clock_control__cycle_count__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__clock_control__go__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__clock_control__bkpt_generic_output_wires__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__clock_control__bkpt_mailbox_data_avail__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__clock_control__bkpt_mailbox_flow_done__out_t;

    typedef struct {
        logic value;
    } caliptra_fpga_sync_regs__clock_control__bkpt_etrng_req__out_t;

    typedef struct {
        caliptra_fpga_sync_regs__clock_control__cycle_count__out_t cycle_count;
        caliptra_fpga_sync_regs__clock_control__go__out_t go;
        caliptra_fpga_sync_regs__clock_control__bkpt_generic_output_wires__out_t bkpt_generic_output_wires;
        caliptra_fpga_sync_regs__clock_control__bkpt_mailbox_data_avail__out_t bkpt_mailbox_data_avail;
        caliptra_fpga_sync_regs__clock_control__bkpt_mailbox_flow_done__out_t bkpt_mailbox_flow_done;
        caliptra_fpga_sync_regs__clock_control__bkpt_etrng_req__out_t bkpt_etrng_req;
    } caliptra_fpga_sync_regs__clock_control__out_t;

    typedef struct {
        logic [63:0] value;
    } caliptra_fpga_sync_regs__counter__counter__out_t;

    typedef struct {
        caliptra_fpga_sync_regs__counter__counter__out_t counter;
    } caliptra_fpga_sync_regs__counter__out_t;

    typedef struct {
        logic req;
        logic [15:0] addr;
        logic req_is_wr;
        logic [63:0] wr_data;
        logic [63:0] wr_biten;
    } caliptra_fpga_sync_regs__rom_mem__external__out_t;

    typedef struct {
        caliptra_fpga_sync_regs__apb_in0__out_t apb_in0;
        caliptra_fpga_sync_regs__apb_in1__out_t apb_in1;
        caliptra_fpga_sync_regs__apb_out__out_t apb_out;
        caliptra_fpga_sync_regs__jtag_in__out_t jtag_in;
        caliptra_fpga_sync_regs__jtag_out__out_t jtag_out;
        caliptra_fpga_sync_regs__generic_input_wires__out_t generic_input_wires;
        caliptra_fpga_sync_regs__generic_output_wires__out_t generic_output_wires;
        caliptra_fpga_sync_regs__cptra_obf_key__out_t cptra_obf_key[4];
        caliptra_fpga_sync_regs__control__out_t control;
        caliptra_fpga_sync_regs__status__out_t status;
        caliptra_fpga_sync_regs__trng_in__out_t trng_in;
        caliptra_fpga_sync_regs__trng_out__out_t trng_out;
        caliptra_fpga_sync_regs__clock_control__out_t clock_control;
        caliptra_fpga_sync_regs__counter__out_t counter;
        caliptra_fpga_sync_regs__rom_mem__external__out_t rom_mem;
    } caliptra_fpga_sync_regs__out_t;
endpackage