name: Size History

on:
  push:
    branches: ["main"]
  pull_request:

  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-22.04

    env:
      RUST_TOOLCHAIN_VERSION: 1.68.0
      CARGO_INCREMENTAL: 0
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Configure actions-cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');


      - name: Set Rust ${{ env.RUST_TOOLCHAIN_VERSION }} as the default toolchain.
        run: |
          rustup default ${RUST_TOOLCHAIN_VERSION}
          rustup target add riscv32imc-unknown-none-elf

      - name: Run size analysis (look at workflow "Summary" tab for results)
        run: |
          export
          cargo run --release -p caliptra-size-history
